#! env ruby
# -*- coding: utf-8 -*-

require_relative 'erlang'

if ARGV.include?("-t") # use tree format

  find_exports.each do |file_path,exports|
    puts "#{File.basename(file_path)}:"
    exports.each_with_index do |export, index|
      if not export.is_otp_export
        if index < exports.length - 1
          puts "├── #{export.to_s}"
        else
          puts "└── #{export.to_s}"
        end
      end
    end
  end

else

  find_exports.each do |file_path,exports|
    exports.each do |export|
      if not export.is_otp_export
        puts "#{file_path}:#{export.name}:#{export.arity}"
      end
    end
  end

end
